# This file was generated by GoReleaser. DO NOT EDIT.
cask "gantry" do
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_amd64.tar.gz"
      sha256 "97c6a2ddf1285fc5e488211dbd31fddcdd24c0e1032c00e0ec8fb6d92c8c35e5"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_arm64.tar.gz"
      sha256 "553457415f981ff05230e95d598d290ea4d9806ae03f5d8a461ee4dada94c7f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_amd64.tar.gz"
      sha256 "6ecf79fde3b45b78708b8bfbb5fe21aba1dc1be19ed6172f7e5c15b8dce4af69"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_arm64.tar.gz"
      sha256 "1780bf1c95b0f71bfac1d1649bfa5f598cb5edddde60b12d8de2fbf23a30526b"
    end
  end

  name "gantry"
  desc "A CLI for Platform-izing devcontainers in microservices, widely distributed, or just complicated™ situations."
  homepage "https://github.com/ivanklee86/gantry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gantry"

  # No zap stanza required

end
