# This file was generated by GoReleaser. DO NOT EDIT.
cask "gantry" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_amd64.tar.gz"
      sha256 "ae1c68c8c8c4f9c7595797b83b884fa111563ed5a740909120d61bd504657210"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_arm64.tar.gz"
      sha256 "fec3ba2b0b64067730580ac628a74d1b551982beaaab1819943fda3bd26e18bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_amd64.tar.gz"
      sha256 "c4d7161185e84872bf05b04871f21f0ecf7a5f68caa4e9d6df09976f0cfdf42a"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_arm64.tar.gz"
      sha256 "1927c7ff48251ddca75b7cdf4aaaa7d5374bd16f0fd3f4eceea3ccdf91ac20bb"
    end
  end

  name "gantry"
  desc "A CLI for Platform-izing devcontainers in microservices, widely distributed, or just complicated™ situations."
  homepage "https://github.com/ivanklee86/gantry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gantry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gantry"]
    end
  end

  # No zap stanza required

end
