# This file was generated by GoReleaser. DO NOT EDIT.
cask "gantry" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_amd64.tar.gz"
      sha256 "256451cf1c1e49ecd6ef7dec47619685857478772204bd9a9d9f4423850fd83f"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_darwin_arm64.tar.gz"
      sha256 "a633262685a394729391e7d62408e6b6f9eb5e56ad99e422839d48762b01499b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_amd64.tar.gz"
      sha256 "876091683ac7b6014bcdb3ac154680cba60b0a6314ec0809e4126a82769b5417"
    end
    on_arm do
      url "https://github.com/ivanklee86/gantry/releases/download/v#{version}/gantry_#{version}_linux_arm64.tar.gz"
      sha256 "14674a91cabc83afe8d680cb331197008c87f1bb04481822308d1f3614ced8ff"
    end
  end

  name "gantry"
  desc "A CLI for Platform-izing devcontainers in microservices, widely distributed, or just complicated™ situations."
  homepage "https://github.com/ivanklee86/gantry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gantry"

  # No zap stanza required

end
