# This file was generated by GoReleaser. DO NOT EDIT.
cask "tangle-cli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "141e66955109c3ac97a71bd0a71ae2795364b0ab3b4598159d5cd80fa5eff182"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c46334753c6a54065653bd323bb255ce62f6ab4baf1d57c7d45451fa4269a81b"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84ca6b8a4a1271881b31d233115c5baff491b46c52028b749847b9201523a74c"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2e3c65054ab61d06bd3fb809b5924a349faa51426bc8c718ddd2366ef1a2735"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tangle-cli"
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tangle-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tangle-cli"]
    end
  end

  # No zap stanza required
end
