# This file was generated by GoReleaser. DO NOT EDIT.
cask "tangle-cli" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "50aed1c58bb9b5dc41c310c8b1f43e2477eacfc36020cede771b3590808cfbde"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "16d597faeec2548a790d131be98460e55c2178b9b5ffea27252b0904efb86a59"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3a1d2125cb2efa1a93d9efbabf72799c3d6594000b7ff98105cd7aac2f6e867b"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "351f053a05a34814cba1304b748900e41a5a6eacc13dba5bcb65599053ea133b"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tangle-cli"
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tangle-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tangle-cli"]
    end
  end

  # No zap stanza required
end
