# This file was generated by GoReleaser. DO NOT EDIT.
cask "tangle-cli" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "6cc860b71f9ed515b1525a35a6c14f822456ee3ac042c1e0466e632b01d5e1dc"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7af7dc5928b9e3e22089fe7e0893f4adb3b5ff36b28e3df61ea613d4e39a9f50"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "802574e9cfda42d983535a3dfd7eb9dd0619ac1ed0266d412fdebbd6718c10d8"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "730a89c25fb955563fc62c9205ef09f884485d33fa4a0e3349cf90904d476814"
      url "https://github.com/ivanklee86/tangle/releases/download/v#{version}/tangle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tangle-cli"
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tangle-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tangle-cli"]
    end
  end

  # No zap stanza required
end
