# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TangleCli < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.1.0/tangle_0.1.0_darwin_amd64.tar.gz"
      sha256 "06a5d06e2f2615fcaecd059fd9741aa2626f6f41c47dab3ff9596d6c29592793"

      def install
        bin.install "tangle-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.1.0/tangle_0.1.0_darwin_arm64.tar.gz"
      sha256 "0132d8dd8111fcb9b854d59a833c423672bc6f1046a696ce639d2f16df5b89db"

      def install
        bin.install "tangle-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.1.0/tangle_0.1.0_linux_amd64.tar.gz"
      sha256 "83320d1c2f51458e49ab93b64d4194ea213abd4ac31f2b5455e7d1ed58754f6c"
      def install
        bin.install "tangle-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.1.0/tangle_0.1.0_linux_arm64.tar.gz"
      sha256 "d36ead7d71cdeafeea684ab426a7a947f89e852b1134ea123fab49fb75c3df23"
      def install
        bin.install "tangle-cli"
      end
    end
  end
end
