# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TangleCli < Formula
  desc "A CLI to configure/clear SyncWindows on ArgoCD projects."
  homepage "https://github.com/ivanklee86/tangle-cli"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.0.13/tangle_0.0.13_darwin_amd64.tar.gz"
      sha256 "ee019a380a1b042371fa9c2ccf5b464e78fd8867b4153f4412680b1bcf43056a"

      def install
        bin.install "tangle-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanklee86/tangle/releases/download/v0.0.13/tangle_0.0.13_darwin_arm64.tar.gz"
      sha256 "fede93e8bbee2b0d6994b66b6e269b3ae73f1f23bcf31da3b4746afc2573aef1"

      def install
        bin.install "tangle-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/tangle/releases/download/v0.0.13/tangle_0.0.13_linux_amd64.tar.gz"
        sha256 "2a8bd5d74029ca613525337e61aaa0e6a88cfc0feb610d64f8d5bd4058b0d987"

        def install
          bin.install "tangle-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivanklee86/tangle/releases/download/v0.0.13/tangle_0.0.13_linux_arm64.tar.gz"
        sha256 "58e827070d63e72a53ab6b9116ff930a7d3efbba17e06330bc0260f2fe94fff9"

        def install
          bin.install "tangle-cli"
        end
      end
    end
  end
end
